services:
  - type: web
    name: nest-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    branch: main
    pullRequestPreviewsEnabled: true
